services:
  db:
    image: mysql:latest
    container_name: encurta_db
    environment:
      - MYSQL_ROOT_PASSWORD=RootPassword
      - MYSQL_USER=Bruno
      - MYSQL_PASSWORD=Bruno123
      - MYSQL_DATABASE=encurta_db

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      timeout: 5s
      interval: 10s
      retries: 10
      # In this situation, doesn't change anything, though I am putting it just to learn about it
      # this applies to the english too
      start_period: 30s
      start_interval: 5s
    ports:
        - "3306:3306"
    volumes:
      - encurta_vl:/var/lib/mysql
    networks:
      - encurta_ntw

# now, i need to study about the difference between volume and bind amount

  backend:
    build: ./backend
    container_name: encurta_back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/encurta_db
      - SPRING_DATASOURCE_USERNAME=Bruno
      - SPRING_DATASOURCE_PASSWORD=Bruno123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - encurta_ntw
volumes:
  encurta_vl:
networks:
  encurta_ntw: