CREATE TABLE urls_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    original_uri VARCHAR(450) NOT NULL,
    short_uri VARCHAR(450) UNIQUE NOT NULL,
    id_owner VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (id_owner) REFERENCES users_tb(id)
    ON DELETE RESTRICT
);